name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Generate Keys
      run: go run m2mams.go g test@test.com

    - name: Sign and Verify Token
      run: go run m2mams.go v $(go run m2mams.go s test@test.com)

    - name: Go Release Binary
      # You may pin to the exact commit or the version.
      # uses: ngs/go-release.action@a32a23d081d503245410d9d7bf59b722b50cc766
      uses: ngs/go-release.action@v1.0.2
